name: "Build docker image"
on:
  push:
    # branches:
    #   - master
    tags:
      - "*"
jobs:
  docker_img:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jlle/clojars
          tag_with_ref: true
